model_definition:
  name: spanish-to-english-seedbank
  author:
    name: <author name>
  description: translate spanish sentences to english
  framework:
    name: tensorflow
    version: "1.5"
  execution:
    command: bash myscript.sh
    compute_configuration:
      name: k80
training_data_reference:
  name: training_data_reference
  connection:
    endpoint_url: "https://s3-api.us-geo.objectstorage.service.networklayer.com"
    access_key_id: "<access_key_id>"
    secret_access_key: "<secret_access_key>"
  source:
    bucket: <source-bucket-name>
  type: s3
training_results_reference:
  name: training_results_reference
  connection:
    endpoint_url: "https://s3-api.us-geo.objectstorage.service.networklayer.com"
    access_key_id: "<access_key_id>"
    secret_access_key: "<secret_access_key>"
  target:
    bucket: <result-bucket-name>
  type: s3
